[tool.poetry]
name = "pynetdicom2"
version = "0.9.8"
description = "pynetdicom2 is a pure python package implementing the DICOM network protocol"
authors = ["Pavel 'Blane' Tuchin <blane.public@gmail.com>"]

license = "MIT"

readme = "README.rst"

keywords = ["medical", "dicom", "network"]

repository = "https://github.com/blanebf/pynetdicom2"
homepage = "https://github.com/blanebf/pynetdicom2"
documentation = "https://pynetdicom2.readthedocs.io/en/latest/"

classifiers = [
    "License :: OSI Approved :: MIT License",
    "Intended Audience :: Developers",
    "Intended Audience :: Healthcare Industry",
    "Intended Audience :: Science/Research",
    "Development Status :: 4 - Beta",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Operating System :: OS Independent",
    "Topic :: Software Development :: Libraries"
]

[tool.poetry.dependencies]
python = "^3.10"
pydicom = "^2.4"

[tool.poetry.dev-dependencies]
pylint = "^3.3.0"

[tool.poetry.group.dev.dependencies]
mypy = "^1.10.1"
flake8 = "^7.3.0"
coverage = "7.10.7"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"

[tool.mypy]
python_version = "3.9"
files = ["pynetdicom2"]
warn_unused_configs = true

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["*TestCase"]

[tool.coverage.run]
source = ["pynetdicom2"]
branch = true

[tool.coverage.report]
show_missing = true
fail_under = 85
exclude_lines = [
    "pragma: no cover",
    "raise NotImplementedError",
    "if __name__ == .__main__.:",
]
