# Copyright (c) 2021 Pavel 'Blane' Tuchin
# Copyright (c) 2012 Patrice Munger
# This file is part of pynetdicom, released under a modified MIT license.
#    See the file license.txt included with this distribution, also
#    available at https://github.com/blanebf/pynetdicom2
"""
This module provides two main classes for working with Application Entities.
You can think of Application Entities as nodes in a DICOM communication, that
provide or use a list of services (hence SCPs and SCU).

Classes in this module are your starting points when working with this library.

If only you require working as SCU (sending verification or making a find
request, for example), you should use
:class:`~pynetdicom2.applicationentity.ClientAE`.

In case you would require services in SCP roles, you should go with
:class:`~pynetdicom2.applicationentity.AE`.

Please refer to base class for each of them
(:class:`~pynetdicom2.applicationentity.AEBase`) for more detailed
information on common principles and options when working with Application
Entities.
"""
from functools import partial
from itertools import count
import threading
import copy
import contextlib
import logging
import pathlib
import platform
import tempfile
import socket
import socketserver
from typing import Any, BinaryIO, Iterator, Iterable, Optional, Union, cast

from pydicom import Dataset, filebase, uid
from pydicom.dataset import FileMetaDataset
from pydicom.filewriter import write_file_meta_info

from . import asceprovider, dimsemessages, exceptions, fsm, statuses, pdu


logger = logging.getLogger(__name__)


# current implementation UID. Generated by pydicom
PREAMBLE = b'\0' * 128 + b'DICM'


def write_meta(fp: BinaryIO, command_set: Dataset, ts: uid.UID) -> None:
    """Writes file meta information.

    This is a small utility function that can be useful when overriding
    :meth:`~pynetdicom2.applicationentity.AEBase.get_file` method of the
    :class:`~pynetdicom2.applicationentity.AEBase` class

    :param fp: file or file-like object where dataset will be stored
    :param command_set: command dataset of received message
    :param ts: dataset transfer syntax
    """
    fp.write(PREAMBLE)
    meta = FileMetaDataset()
    meta.MediaStorageSOPClassUID = command_set.AffectedSOPClassUID
    meta.MediaStorageSOPInstanceUID = command_set.AffectedSOPInstanceUID
    meta.TransferSyntaxUID = ts
    meta.ImplementationClassUID = asceprovider.IMPLEMENTATION_UID
    write_file_meta_info(filebase.DicomFileLike(fp), meta)


class AEBase:
    """Base Application Entity class.

    This class is intended for sub-classing and should not be used directly.
    Use :class:`~pynetdicom2.applicationentity.ClientAE` or
    :class:`~pynetdicom2.applicationentity.AE` instead

    Class provides common API for application entities, such as:
        * requesting association
        * adding services as SCU
        * handful of useful public properties (presentation context definition
          list, supported transfer syntax list, maximum pdu size)

    :ivar supported_ts:  Set of transfer syntaxes supported by this
                         application entity. This attribute defaults to
                         :attr:`pynetdicom2.applicationentity.AEBase.default_ts`.
    :ivar timeout: Connection timeout in seconds. Default value is 15.
    :ivar max_pdu_length: Maximum size of PDU in bytes.
    :ivar supported_scu: Dictionary that maps Abstract syntax UIDs to specific
                         services that are support in SCU role.
                         This attribute is populated by adding services using
                         :meth:`~pynetdicom2.applicationentity.AEBase.add_scu`
                         method.
                         This attribute is intended for **read-only** use
                         by class clients.

    :ivar supported_scp: Dictionary that maps Abstract syntax UIDs to
                         specific services that are support in SCP role.
                         This attribute is populated by adding services using
                         :meth:`~pynetdicom2.applicationentity.AE.add_scp`
                         method of the full AE class
                         This attribute is intended for **read-only** use by
                         class clients.

    """
    default_ts = [
        uid.ExplicitVRLittleEndian,
        uid.ImplicitVRLittleEndian,
        uid.ExplicitVRBigEndian
    ]

    """
    Default list of supported transfer syntaxes.
    """

    def __init__(
            self,
            supported_ts: Optional[list[uid.UID]],
            max_pdu_length: int,
            ae_title: str,
            port: Optional[int] = None
    ) -> None:
        if supported_ts is None:
            supported_ts = self.default_ts

        self.local_ae = asceprovider.AETParams(
            address=platform.node(),
            aet=ae_title,
            port=port
        )

        self.supported_ts = frozenset(supported_ts)
        self.dcm_timeout: int = 15
        self.artim_timeout: int = 10
        self.max_pdu_length = max_pdu_length

        self.context_def_list: dict[int, asceprovider.PContextDefList] = {}
        self.store_in_file: set[uid.UID] = set()
        self.supported_scu: dict[
            uid.UID, asceprovider.SCUServiceWithSOPClass
        ] = {}
        self.supported_scp: dict[
            uid.UID,
            asceprovider.SCPServiceWithSOPClass[
                dimsemessages.DIMSERequestMessage
            ]
        ] = {}
        self.lock = threading.Lock()

    def add_scu(
            self,
            service: asceprovider.SCUServiceWithSOPClass,
            sop_classes: Optional[list[uid.UID]] = None
    ) -> asceprovider.AEBaseProto:
        """Adds service as SCU to the AE.

        Presentation context definition list is updated based on SOP Class UIDs
        that are handled by this service. Calls to this method could be
        chained, so you can add multiple services in one statement.

        :param service: DICOM service
        :param sop_classes: overrides list of SOP Class UIDs provided by the
                            service
        """
        sop_classes = sop_classes or service.sop_classes
        self.supported_scu.update({uid: service for uid in sop_classes})
        store_in_file = (
            hasattr(service, 'store_in_file') and service.store_in_file
        )
        self.update_context_def_list(sop_classes, store_in_file)
        return self

    def update_context_def_list(
            self, sop_classes: Iterable[uid.UID], store_in_file: bool = False
    ) -> None:
        """Updates presentation context definition list.

        :param sop_classes: new SOP Class UIDs that should be added to
                            presentation contexts definition list
        :param store_in_file: indicates if incoming datasets for these SOP
                              Classes should be stored in file.
        """
        start = (
            max(self.context_def_list.keys()) + 2 if self.context_def_list
            else 1
        )

        self.context_def_list.update(
            self._build_context_def_list(sop_classes, start, store_in_file)
        )

    def copy_context_def_list(self) -> dict[int, asceprovider.PContextDefList]:
        """Makes a shallow copy of presentation context definition list.

        .. note::

            This method is tread-safe.

        :return: copy of the presentation context definition list.
        """
        with self.lock:
            return copy.copy(self.context_def_list)

    @contextlib.contextmanager
    def request_association(
            self,
            remote_ae: Union[asceprovider.RemoteAEConfig, dict[str, Any]]
    ) -> Iterator[asceprovider.AssociationRequester]:
        """Requests association to a remote application entity.

        Request is formed based on configuration dictionary that is passed in.
        Currently supported parameters are:

            * **aet** - remote AE title
            * **address** - remote AE IP address
            * **port** - remote AE port
            * **username** - username for DICOM authentication
            * **password** - password for DICOM authentication

        :param remote_ae: dictionary that contains remote AE configuration.
        """
        assoc = None
        try:
            assoc = self._create_association(remote_ae)
            assoc.request()
            yield assoc
            if assoc.association_established:
                assoc.release()
            else:
                assoc.kill()
        except Exception:
            if assoc and assoc.association_established:
                assoc.abort()
            elif assoc:
                assoc.kill()
            raise

    def get_file(
            self,
            context: fsm.PContextDef,
            command_set: Dataset
    ) -> tuple[BinaryIO, int]:
        """Method is used by association to get file-like object to store
        dataset.

        Method is only called when service SOP Class UID is present in
        `self.store_in_file` set. Method itself does not own the file object.
        So it's service implementation responsibility to close the file after
        it's done when handling received message.
        Default implementation is based on a temporary file. User may choose
        to override this method to provide a permanent storage for dataset.

        :param context: presentation context
        :param command_set: command dataset of the received message
        :return: file where association can store received dataset and file
                 starting position.
        """
        tmp = tempfile.TemporaryFile()  # pylint: disable=consider-using-with
        start = tmp.tell()
        try:
            write_meta(tmp, command_set, context.supported_ts)
        except Exception:
            tmp.close()
            raise
        return tmp, start

    def on_association_request(
            self,
            asce: asceprovider.AssociationAcceptor,
            assoc: pdu.AAssociateRqPDU
    ) -> None:
        """Extra processing of the association request.

        Default implementation of the method does nothing and thus accepts all
        incoming association requests.
        If association should be rejected user should override this method
        in a sub-class and raise `AssociationRejectedError` when appropriate

        :param asce: association object itself
        :param assoc: association request parameters
        """

    def on_association_response(self, response: pdu.AAssociateAcPDU) -> None:
        """Extra processing for association response.

        Default implementation does nothing.

        :param response: response received from remote AE
        """

    def on_abort(
            self,
            asce: asceprovider.Association,
            exc: exceptions.AssociationAbortedError
    ) -> None:
        """Called to handle
        :class:`~pynetdicom2.exceptions.AssociationAbortedError`
        """
        logger.warning('Association [%d] was aborted: %r', id(asce), exc)

    def on_dcm_timeout(
            self,
            asce: asceprovider.Association,
            exc: exceptions.DCMTimeoutError
    ) -> None:
        """Called to handle :class:`~pynetdicom2.exceptions.DCMTimeoutError`"""
        logger.warning('Association [%d] timed out: %r', id(asce), exc)

    def on_receive_echo(  # pylint: disable=unused-argument
            self,
            context: fsm.PContextDef
    ) -> statuses.Status:
        """Default handling of C-ECHO command. Always returns SUCCESS code

        User should override this method in a sub-class to provide custom
        handling of the command.

        :param context: presentation context (contains ID, SOP Class UID and
                        Transfer Syntax)
        :return: status that should be sent in response
        """
        return statuses.SUCCESS

    def on_receive_store(  # pylint: disable=unused-argument
            self,
            context: fsm.PContextDef,
            ds: Union[BinaryIO, bytes]
    ) -> statuses.Status:
        """Default handling of C-STORE command. Always returns
        ELEMENT_DISCARDED code.

        User should override this method in a sub-class to provide custom
        handling of the command

        :param context: presentation context (contains ID, SOP Class UID and
                        Transfer Syntax)
        :param ds: dataset that should be stored
        :return: status code
        """
        return statuses.C_STORE_ELEMENTS_DISCARDED

    def on_receive_find(  # pylint: disable=unused-argument
            self,
            context: fsm.PContextDef,
            ds: Dataset
    ) -> Iterator[tuple[Dataset, statuses.Status]]:
        """Default handling of C-FIND command. Returns empty iterator.

        :param context: presentation context (contains ID, SOP Class UID and
                        Transfer Syntax)
        :param ds: dataset with C-FIND parameters
        :return: iterator that returns tuples: (<result dataset>,
                 <status code>)
        """
        return iter([])

    def on_receive_move(
            self,
            context: fsm.PContextDef,
            ds: Dataset,
            destination: str
    ) -> tuple[asceprovider.RemoteAEConfig, int, Iterator[Dataset]]:
        """Default handling of C-MOVE command. Returns empty empty values

        :param context: presentation context (contains ID, SOP Class UID and
                        Transfer Syntax)
        :param ds: dataset with C-MOVE parameters
        :param destination: C-MOVE command destination
        :return: tuple: remote AE parameters, number of operations and iterator
                 that will return datasets for moving
        """
        raise exceptions.EventHandlingError('Not implemented')

    def on_commitment_request(
            self,
            remote_ae: str,
            uids: Iterable[tuple[uid.UID, uid.UID]]
    ) -> tuple[
        asceprovider.RemoteAEConfig,
        Iterable[tuple[uid.UID, uid.UID]],
        Iterable[tuple[uid.UID, uid.UID, int]]
    ]:
        """Handle storage commitment request.

        Method should return three values:
            * remote AE parameters (IP address, port, etc.)
            * iterable or None for successfully stored SOP Instance UIDs
            * iterable or None for failed SOP Instance UIDs

        Default implementation is not provided. Method raises
        `exceptions.EventHandlingError`

        :param remote_ae: remote AE title
        :param uids: iterable of tuples (SOP Class UID, SOP Instance UID)
        """
        raise exceptions.EventHandlingError('Not implemented')

    def on_commitment_response(
            self,
            transaction_uid: uid.UID,
            success: Iterable[tuple[uid.UID, uid.UID]],
            failure: Iterable[tuple[uid.UID, uid.UID, int]]
    ) -> None:
        """Handle storage commitment response.

        Default implementation is not provided. Method raises
        `exceptions.EventHandlingError`

        :param transaction_uid: Transaction UID
        :param success: iterable of tuples (SOP Class UID, SOP Instance UID)
        :param failure: iterable of tuples (SOP Class UID, SOP Instance UID,
                        Failure Reason)
        """
        raise exceptions.EventHandlingError('Not implemented')

    def _create_association(
            self,
            remote_ae: Union[asceprovider.RemoteAEConfig, dict[str, Any]]
    ) -> asceprovider.AssociationRequester:
        return asceprovider.AssociationRequester(
            self, self.max_pdu_length, remote_ae
        )

    def _build_context_def_list(
            self,
            sop_classes: Iterable[uid.UID],
            start: int,
            store_in_file: bool
    ) -> dict[int, asceprovider.PContextDefList]:
        if store_in_file:
            self.store_in_file.update(sop_classes)
        return {
            pc_id: asceprovider.PContextDefList(
                pc_id, sop_class, self.supported_ts
            )
            for sop_class, pc_id in zip(sop_classes, count(start, 2))
        }


class ClientAE(AEBase):
    """Simple SCU-only application entity.

    Use this class if you only intend to use SCUs service roles. This AE won't
    handle any incoming connections.

    :param ae_title: AE title (up to 16 characters)
    :param supported_ts: list of supported transfer syntaxes. If you are
                         using Storage or Q/R C-GET services be sure to
                         add only transfer syntax of the expected dataset.
    :param max_pdu_length: maximum PDU length in bytes (defaults to 64kb).
    """
    def __init__(
            self,
            ae_title: str,
            supported_ts: Optional[list[uid.UID]] = None,
            max_pdu_length: int = 65536
    ) -> None:
        """Initializes new ClientAE instance"""
        super().__init__(supported_ts, max_pdu_length, ae_title)


class RequestHandler(socketserver.StreamRequestHandler):
    """Request handler for incoming TCP connections. Used to establish
    association and is not inteded to be used directly.
    """
    def __init__(
            self,
            request: socket.socket,
            client_address: tuple[str, int],
            server: socketserver.ThreadingTCPServer,
            local_ae: asceprovider.AEBaseProto,
            max_pdu_length: int
    ) -> None:
        self.asce = asceprovider.AssociationAcceptor(
            request, local_ae, max_pdu_length
        )
        super().__init__(request, client_address, server)

    def handle(self) -> None:
        self.asce.handle()


class _ThreadingTCPServer(socketserver.ThreadingTCPServer):
    """Threading TCP server with the defaults used by DICOM SCPs.

    ``allow_reuse_address`` must be set before the socket is bound. As the
    binding happens inside ``__init__`` (when ``bind_and_activate`` is true),
    both attributes are defined on the class rather than set on the instance.
    """
    allow_reuse_address = True
    daemon_threads = True


class AE(AEBase):
    """Represents a DICOM application entity based on
    ``SocketServer.ThreadingTCPServer``

    Unlike :class:`~pynetdicom2.applicationentity.ClientAE` this one is fully
    functional application entity that can take on both SCU and SCP roles.
    For convenience :class:`~pynetdicom2.applicationentity.AE` supports context
    manager interface so it can be used like this::

        from pynetdicom2.sopclass import verification_scp

        ae = AE('AET', 104).add_scp(verification_scp)
        with ae:
            pass  # AE is running and accepting connection.

    Upon exiting context AE is stopped.

    :param ae_title: AE title (up to 16 characters)
    :param port: port that AE listens on for incoming connection
    :param supported_ts: list of transfer syntaxes supported by AE
    :param max_pdu_length: maximum PDU length in bytes (defaults to 64kb).
    """

    def __init__(
            self,
            ae_title: str,
            port: int,
            supported_ts: Optional[list[uid.UID]] = None,
            max_pdu_length: int = 65536,
            bind_and_activate: bool = True
    ) -> None:
        """Initializes new AE instance."""
        super().__init__(supported_ts, max_pdu_length, ae_title, port)
        self.server = self._create_server(
            port, bind_and_activate, max_pdu_length
        )
        self.activted = bind_and_activate

    def add_scp(
            self,
            service: asceprovider.SCPServiceWithSOPClass[asceprovider.T_contra]
    ) -> 'AE':
        """Adds service as SCP to the AE.

        Method is similar to ``add_scu`` method of the
        :class:`~pynetdicom2.applicationentity.AEBase` base class.

        :param service: DICOM service.
        """
        self.supported_scp.update({
            uid: cast(
                asceprovider.SCPServiceWithSOPClass[
                    dimsemessages.DIMSERequestMessage
                ],
                service
            )
            for uid in service.sop_classes
        })
        store_in_file = (
            hasattr(service, 'store_in_file') and service.store_in_file
        )
        self.update_context_def_list(service.sop_classes, store_in_file)
        return self

    def quit(self) -> None:
        """Stops AE from accepting any more connections."""
        self.server.shutdown()
        self.server.server_close()

    def _create_server(
            self,
            port: int,
            bind_and_activate: bool,
            max_pdu_length: int
    ) -> socketserver.TCPServer:
        return _ThreadingTCPServer(
            ('', port),
            partial(
                RequestHandler,
                local_ae=self,
                max_pdu_length=max_pdu_length
            ),
            bind_and_activate
        )

    def __enter__(self) -> 'AE':
        if not self.activted:
            try:
                self.server.server_bind()
                self.server.server_activate()
            except:  # noqa E722
                self.server.server_close()
                raise
        threading.Thread(target=self.server.serve_forever).start()
        return self

    def __exit__(self, *args: Any) -> None:
        self.quit()


class FolderStorageMixin:
    """Mixin that add creating a storage file object, based on incoming
    command dataset.

    Provides methods for getting unique filename name in a provided folder and
    creating storage file.
    """

    max_iterations: int = 10
    """
    Maximum iteration for looking for a unique filename
    """

    def get_file_name(
            self,
            path: pathlib.Path,
            sop_instance_uid: uid.UID
    ) -> pathlib.Path:
        """Gets a unique filename in a folder, where incoming dataset should
        be stored.

        Method uses SOP Instance UID of incoming dataset

        :param path: path to a folder where the storage should be created
        :param sop_instance_uid: incoming SOP Instance UID
        :raises OSError: raised if method fails to obtain unique filename for
                         storing incoming dataset
        :return: unique filename to store incoming dataset
        """
        i = 0
        full_name = path / f'{sop_instance_uid}.dcm'
        while full_name.exists():
            i += 1
            if i > self.max_iterations:
                raise OSError('Max iteration for free filename reached')
            full_name = path / f'{sop_instance_uid}_{i}.dcm'
        return full_name

    def get_storage_file(
            self,
            context: fsm.PContextDef,
            command_set: Dataset,
            path: pathlib.Path
    ) -> tuple[BinaryIO, int]:
        """Gets a bytes IO and starting point in it for storing incoming
        dataset.

        :param context: presentation context
        :param command_set: incoming command dataset
        :param path: path to a folder where incoming dataset should be stored
        :return: tuple of bytes IO and starting point in it
        """
        full_name = self.get_file_name(
            path, command_set.AffectedSOPInstanceUID
        )

        ds = open(full_name, 'w+b')  # pylint: disable=consider-using-with
        start = ds.tell()
        try:
            write_meta(ds, command_set, context.supported_ts)
        except Exception:
            ds.close()
            raise
        return ds, start


class ClientStorageAE(ClientAE, FolderStorageMixin):
    """Helpful client AE class, that stores incoming dataset over Storage
    service in a folder.

    :ivar storage_dir: a folder where incoming datasets should be stored
    """
    def __init__(
            self,
            storage_dir: pathlib.Path,
            ae_title: str,
            supported_ts: Optional[list[uid.UID]] = None,
            max_pdu_length: int = 65536
    ) -> None:
        super().__init__(ae_title, supported_ts, max_pdu_length)
        self.storage_dir = storage_dir

    def get_file(
            self, context: fsm.PContextDef, command_set: Dataset
    ) -> tuple[BinaryIO, int]:
        return self.get_storage_file(context, command_set, self.storage_dir)


class StorageAE(AE, FolderStorageMixin):
    """Helpful AE class, that stores incoming dataset over Storage service
    in a folder.

    :ivar storage_dir: a folder where incoming datasets should be stored
    """
    def __init__(
            self,
            storage_dir: pathlib.Path,
            ae_title: str,
            port: int,
            supported_ts: Optional[list[uid.UID]] = None,
            max_pdu_length: int = 65536,
            bind_and_activate: bool = True
    ) -> None:
        super().__init__(
            ae_title,
            port,
            supported_ts,
            max_pdu_length,
            bind_and_activate
        )
        self.storage_dir = storage_dir

    def get_file(
            self, context: fsm.PContextDef, command_set: Dataset
    ) -> tuple[BinaryIO, int]:
        return self.get_storage_file(context, command_set, self.storage_dir)
